apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-helse-spre-arbeidsgiver
  namespace: tbd
  labels:
    team: tbd
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 2
    retentionBytes: -1
    retentionHours: 2201
  acl:
    - team: tbd
      application: spre-arbeidsgiver
      access: readwrite
    - team: helsearbeidsgiver
      application: im-varsel
      access: read