---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
    name: spre-oppgaver
    namespace: tbd
    labels:
        team: tbd
    annotations:
        dcat.data.nav.no/title: "spre-oppgaver"
        dcat.data.nav.no/description: "Styrer oppretting av oppgaver i gosys"
        dcat.data.nav.no/theme: "helse"
        dcat.data.nav.no/keyword: "helse, sykepenger, oppgaveopprettelse i gosys"
spec:
    pool: nav-prod
    config:  # optional; all fields are optional too; defaults shown
        cleanupPolicy: delete  # delete, compact
        minimumInSyncReplicas: 1
        partitions: 3
        replication: 2  # see min/max requirements
        retentionBytes: -1  # -1 means unlimited
        retentionHours: 168  # -1 means unlimited
    acl:
        - team: tbd
          application: spre-oppgaver
          access: readwrite
        - team: tbd
          application: spangre-utsettelser
          access: readwrite
        - team: flex
          application: sykepengesoknad-arkivering-oppgave
          access: read
        - team: helsearbeidsgiver
          application: syfoinntektsmelding
          access: read
