kafkaPool: nav-dev
kafkaConsumerGroup: tbd-spre-styringsinfo-v3
kafkaResetPolicy: earliest
livenessInitialDelay: 30
readinessInitialDelay: 30
recreateStrategy: true
app:
  leaderElection: true
gcp:
  type: POSTGRES_15
  databaseName: spre-styringsinfo
  envVarPrefix: DATABASE
  datastream: true
  sqlInstanceTier: db-f1-micro
azure:
  enabled: true
  tenant: trygdeetaten.no
accessPolicy:
  outbound:
    - application: nom-api
      namespace: nom
    - application: speed-api
env:
  - name: NOM_API_BASE_URL
    value: http://nom-api.nom.svc.cluster.local
  - name: NOM_API_OAUTH_SCOPE
    value: api://dev-gcp.nom.nom-api/.default