strategy: Recreate
kafkaPool: nav-prod
kafkaConsumerGroup: tbd-spre-styringsinfo-v3
kafkaResetPolicy: earliest
livenessInitialDelay: 300
readinessInitialDelay: 300
gcp:
  type: POSTGRES_15
  databaseName: spre-styringsinfo
  envVarPrefix: DATABASE
  datastream: true