kafkaPool: nav-prod
kafkaConsumerGroup: tbd-spre-styringsinfo-v3
kafkaResetPolicy: earliest
livenessInitialDelay: 30
readinessInitialDelay: 30
maxMemory: 2Gi
recreateStrategy: true
app:
  leaderElection: true
gcp:
  type: POSTGRES_17
  databaseName: spre-styringsinfo
  envVarPrefix: DATABASE
  datastream: true
azure:
  enabled: true
accessPolicy:
  outbound:
    - application: nom-api
      namespace: nom
    - application: speed-api
env:
  - name: NOM_API_BASE_URL
    value: http://nom-api.nom.svc.cluster.local
  - name: NOM_API_OAUTH_SCOPE
    value: api://prod-gcp.nom.nom-api/.default
