strategy: Recreate
kafkaPool: nav-prod
kafkaConsumerGroup: tbd-spre-styringsinfo-v2
kafkaResetPolicy: earliest
gcp:
  type: POSTGRES_15
  databaseName: spre-styringsinfo
  envVarPrefix: DATABASE
  datastream: true