annotations:
  - key: config.linkerd.io/proxy-outbound-connect-timeout
    value: 10s
replicas:
  min: 1
  max: 1
kafkaPool: nav-dev
azure:
  enabled: true
  tenant: trygdeetaten.no
gcp:
  type: POSTGRES_17
  databaseName: spre-gosys
  envVarPrefix: DB
  sqlInstanceTier: db-f1-micro
accessPolicy:
  outbound:
    - application: speed-api
    - application: spre-gosys-pdf
  external:
    - dokarkiv.dev-fss-pub.nais.io
    - ereg-services-q1.dev-fss-pub.nais.io
env:
  - name: KAFKA_MAX_RECORDS
    value: "50"
  - name: KAFKA_MAX_POLL_INTERVAL_MS
    value: "500000"
  - name: JOARK_BASE_URL
    value: https://dokarkiv.dev-fss-pub.nais.io
  - name: JOARK_SCOPE
    value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
  - name: EREG_BASE_URL
    value: https://ereg-services-q1.dev-fss-pub.nais.io
