annotations:
  - key: config.linkerd.io/proxy-outbound-connect-timeout
    value: 10s
kafkaPool: nav-prod
replicas:
  max: 6
azure:
  enabled: true
gcp:
  type: POSTGRES_15
  databaseName: spre-gosys
  envVarPrefix: DB
accessPolicy:
  outbound:
    - application: speed-api
    - application: spre-gosys-pdf
  external:
    - dokarkiv.prod-fss-pub.nais.io
    - ereg-services.prod-fss-pub.nais.io
env:
  - name: KAFKA_MAX_RECORDS
    value: "50"
  - name: KAFKA_MAX_POLL_INTERVAL_MS
    value: "500000"
  - name: JOARK_BASE_URL
    value: https://dokarkiv.prod-fss-pub.nais.io
  - name: JOARK_SCOPE
    value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
  - name: EREG_BASE_URL
    value: https://ereg-services.prod-fss-pub.nais.io
