---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
    name: forelagte-opplysninger
    namespace: tbd
    labels:
        team: tbd
    annotations:
        dcat.data.nav.no/title: "forelagte-opplysninger"
        dcat.data.nav.no/description: "Forelegger relevant informasjon til den sykmeldte"
        dcat.data.nav.no/theme: "helse"
        dcat.data.nav.no/keyword: "helse, sykepenger, forelegge informasjon"
spec:
    pool: nav-prod
    config:  # optional; all fields are optional too; defaults shown
        cleanupPolicy: delete  # delete, compact
        minimumInSyncReplicas: 1
        partitions: 3
        replication: 2  # see min/max requirements
        retentionBytes: -1  # -1 means unlimited
        retentionHours: 2160  # 83 dager lagring på treig disk
    acl:
        - team: tbd
          application: spre-sykmeldt
          access: readwrite
        - team: flex
          application: flex-inntektsmelding-status
          access: read
