kafkaPool: nav-dev
replicas:
  min: 0
  max: 0
gcp:
  type: POSTGRES_12
  databaseName: spre-saksbehandlingsstatistikk
  sqlInstanceTier: db-f1-micro
kafkaConsumerGroup: tbd-spre-saksbehandlingsstatistikk-v6
kafkaResetPolicy: earliest
env:
  - name: KAFKA_EXTRA_TOPIC
    value: tbd.temp-dokumenter-v1
