name: aiven - Deploy Kafka-topics

on:
  push:
    branches:
      - main
    paths:
      - 'config/oppgaver/aiven-dev-spre-oppgaver.yml'
      - 'config/oppgaver/aiven-prod-spre-oppgaver.yml'
      - 'config/sykmeldt/aiven-dev-forelagte-opplysninger.yml'
      - '.github/workflows/aiven.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write # for nais login

jobs:
  deploy-dev:
    name: apply kafka-topic i dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write # for nais login
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: NAIS login
        uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
        with:
          team: tbd

      - name: Deploy
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: config/oppgaver/aiven-dev-spre-oppgaver.yml,config/sykmeldt/aiven-dev-forelagte-opplysninger.yml

  deploy-prod:
    name: apply kafka-topic i prod
    needs: deploy-dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write # for nais login
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: NAIS login
        uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
        with:
          team: tbd

      - name: Deploy
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: config/oppgaver/aiven-prod-spre-oppgaver.yml
